
var game = {

	id: null, //generated by the server and returned to client in game.search.request(). To be passed in every AJAX call to server afterwards

	search: {

		cancel: function(){
			$('#modal-searchgame').css('display', 'none');
			$('body > *').removeClass('blur');
			$('#searchgame-status').css("background-image", "none").empty();
			
			//send request to the DB to cancel a game, i.e. delete from the DB

			console.log('GameID ' +game.id+' will be cancelled');
		},

		responses: { //methods within this object to be called depending on the request result returned by the server.

			gameCreated: function(gameData){
				game.id = gameData.gameID;
				console.log('GameID is: ' +game.id);
				$('body > *').not('body > #modal-searchgame').addClass('blur');
				$('#modal-searchgame').css('display', 'flex');
				$('#searchgame-status').css("background-image", "url(../img/signup/spinner.gif)")

				//send ping every 2 seconds for the duration of 45 seconds to see if anyone joins the game.
				// create interval variable
				// setInterval for 2 seconds
				// if server anserws that game is too old (UNIX timestamp) then clearInterval -> print error that opponent could not be found.


			},

			gameJoined: function(gameData){


			}
		},

		request: function(){
			console.log(' -> game.play() lunched');
			var data = {action:'play'};			
			$.ajax({
				url: '../php/ajaxhandler.php',
				dataType: 'json',
				type: 'post',
				data: data,
				success: function(response){
					game.search.responses[response.msg](response);					
				}
			});	
		}
	}
};

